name: Release package

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: 📦 Create GitHub release and publish to npmjs
    runs-on: ubuntu-latest

    steps:
      - name: Ensure main branch
        if: github.ref != 'refs/heads/main'
        run: |-
          echo "Not running on main - exit"
          exit 1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@lukso'
          cache: 'yarn'

      - name: 🔍 Check if version changed
        uses: EndBug/version-check@v2
        if: github.event_name == 'push'
        id: check

      - name: 🔄 Check if should release
        run: echo "SHOULD_RELEASE=${{ steps.check.outputs.changed == 'true' || github.event_name == 'workflow_dispatch' }}" >> $GITHUB_ENV

      - name: 📝 Set Version
        if: env.SHOULD_RELEASE == 'true'
        run: |-
          APP_VERSION="v$(node -pe "require('./package.json').version")"
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: 🧰 Install
        if: env.SHOULD_RELEASE == 'true'
        run: yarn

      - name: 🧹 Lint
        if: env.SHOULD_RELEASE == 'true'
        run: yarn lint

      - name: 🛠 Build
        if: env.SHOULD_RELEASE == 'true'
        run: yarn build

      # We assume this will be always triggered by a merge from develop
      # Therefore we tag the previous commit (the merge commit won't be on develop)
      - name: 🏷 Create and push Git Tag
        if: env.SHOULD_RELEASE == 'true'
        run: |-
          git config --global user.email "release@lukso.network"
          git config --global user.name "LUKSO Bot"
          git tag -a ${{ env.APP_VERSION }} HEAD~ -m "Release Version ${{ env.APP_VERSION }} [CI]"
          git push --set-upstream origin tag ${{ env.APP_VERSION }}

      # Create GitHub Release
      - name: 📝 Extract release notes from CHANGELOG
        if: env.SHOULD_RELEASE == 'true'
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          release_notes_file: RELEASENOTES.md

      - name: Add PR body to Release Notes
        if: env.SHOULD_RELEASE == 'true'
        env:
          PR_BODY: ${{ steps.findPR.outputs.body }}
        run: |-
          echo ${PR_BODY}|cat - RELEASENOTES.md > /tmp/out && mv /tmp/out RELEASENOTES.md

      - name: 🚀 Create GitHub release
        if: env.SHOULD_RELEASE == 'true'
        uses: ncipollo/release-action@v1
        with:
          bodyFile: 'RELEASENOTES.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.APP_VERSION }}

      # Publish to NPM
      - name: Publish
        if: env.SHOULD_RELEASE == 'true'
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
